[package]
name = "digital_blasphemy_client"
version = "0.1.1"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
reqwest = { version = "0.12.22", features = ["json"] }
log = "0.4.27"
